//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trifenix.connect.agro.tests.data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntitySearchMgmtResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitySearchMgmtResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trifenix.connect.agro.tests.data.EntitySearchMgmtResults", typeof(EntitySearchMgmtResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;9aebaf15-eb85-49d7-acca-643329d4078b&quot;,&quot;created&quot;:&quot;2020-10-19T17:40:09.8572148-03:00&quot;,&quot;index&quot;:12,&quot;bl&quot;:[],&quot;dbl&quot;:[],&quot;dt&quot;:[],&quot;enm&quot;:[{&quot;facet&quot;:&quot;0,0&quot;,&quot;index&quot;:0,&quot;value&quot;:0}],&quot;num32&quot;:[],&quot;num64&quot;:[],&quot;rel&quot;:[{&quot;index&quot;:7,&quot;id&quot;:&quot;9aebaf15-eb85-49d7-acca-643329d4078b&quot;,&quot;facet&quot;:&quot;7,9aebaf15-eb85-49d7-acca-643329d4078b&quot;},{&quot;index&quot;:32,&quot;id&quot;:&quot;9aebaf15-eb85-49d7-acca-643329d4078b&quot;,&quot;facet&quot;:&quot;32,9aebaf15-eb85-49d7-acca-643329d4078b&quot;}],&quot;str&quot;:[],&quot;sug&quot;:[{&quot;value&quot;:&quot;Producto 1&quot;,&quot;index&quot;:1},{&quot;value&quot;:&quot;12234&quot;,&quot;index&quot;:14}],&quot;geo&quot;:[]}].
        /// </summary>
        internal static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
    }
}
