# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'



  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: './trifenix.connect.agro.tests/trifenix.connect.agro.tests.csproj'
      arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory)'
      publishTestResults: false
      testRunTitle: 'testing agro-fenix'
    displayName: 'Testeando agro-fenix'
  
  - task: PublishTestResults@2    
    inputs:
      testResultsFormat: 'VSTest'
      searchFolder: '$(Agent.TempDirectory)'
      testResultsFiles: '**/*.trx'
      testRunTitle: 'Mostrando resultados de test'
    displayName: 'Publicando resultados de test unitarios'

  - task : DotNetCoreCLI@0
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/*trifenix.agro.functions.csproj'    
      arguments: '--no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'artifactAgroDev'
      publishLocation: 'Container'