//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trifenix.connect.agro.queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchQueryRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchQueryRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trifenix.connect.agro.queries.SearchQueryRes", typeof(SearchQueryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to str/any(element: element/index eq {0}) and (id eq &apos;{1}&apos;).
        /// </summary>
        public static string ELEMENTS_WITHSTRINDEX_AND_IDS {
            get {
                return ResourceManager.GetString("ELEMENTS_WITHSTRINDEX_AND_IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index eq {0}.
        /// </summary>
        public static string ENTITIES_BYINDEX {
            get {
                return ResourceManager.GetString("ENTITIES_BYINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index eq {0}  and rel/any(elementId: elementId/index eq {1} and elementId/id eq &apos;{2}&apos;).
        /// </summary>
        public static string ENTITIES_WITH_ENTITYID {
            get {
                return ResourceManager.GetString("ENTITIES_WITH_ENTITYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index eq {0} and  id ne &apos;{3}&apos; and rel/any(elementId: elementId/index eq {1} and elementId/id eq &apos;{2}&apos;).
        /// </summary>
        public static string ENTITIES_WITH_ENTITYID_EXCEPTID {
            get {
                return ResourceManager.GetString("ENTITIES_WITH_ENTITYID_EXCEPTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index eq {0} and id eq &apos;{1}&apos;.
        /// </summary>
        public static string GET_ELEMENT {
            get {
                return ResourceManager.GetString("GET_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; or id eq &apos;.
        /// </summary>
        public static string IDS_JOIN {
            get {
                return ResourceManager.GetString("IDS_JOIN", resourceCulture);
            }
        }
    }
}
